### PR TITLE
Adding support for floating ip commands

### PR DESCRIPTION
**Pull request by Vasu1105**
Added support to 
> list floating ip
> allocate floating ip
> release floating ip
> associate floating ip
> disassociate floating ip

### CODE REVIEW

**Comment by jjasghar** [comment]
Nice! Great start on this issue.

**Comment by NimishaS** [comment]
@jjasghar , can you please review this?

**Comment by jjasghar** [comment]
Will do first thing on Monday.

**Comment by jjasghar** [comment]
This looks good apart from the couple changes i asked in: https://github.com/chef/knife-openstack/pull/170

**Pull request merged**
